### ISSUE TITLE
Unable to start dev-server on ux32vd

### ISSUE THREAD

**Issue by patrickdoane** [patrickdoane/patrickdoane.com#47]

**Comment by patrickdoane** [comment]
Stack trace
---
```
TypeError: undefined is not a function
    at NpmInstallPlugin.preCompile (/home/bigpp/projects/patrickdoane.com/node_modules/npm-install-webpack-plugin/src/plugin.js:60:25)
    at Compiler.applyPluginsAsync (/home/bigpp/projects/patrickdoane.com/node_modules/webpack/node_modules/tapable/lib/Tapable.js:71:13)
    at Watching._go (/home/bigpp/projects/patrickdoane.com/node_modules/webpack/lib/Compiler.js:44:16)
    at Watching.<anonymous> (/home/bigpp/projects/patrickdoane.com/node_modules/webpack/lib/Compiler.js:36:8)
    at Compiler.readRecords (/home/bigpp/projects/patrickdoane.com/node_modules/webpack/lib/Compiler.js:302:10)
    at new Watching (/home/bigpp/projects/patrickdoane.com/node_modules/webpack/lib/Compiler.js:33:16)
    at Compiler.watch (/home/bigpp/projects/patrickdoane.com/node_modules/webpack/lib/Compiler.js:161:17)
    at module.exports (/home/bigpp/projects/patrickdoane.com/node_modules/webpack-dev-server/node_modules/webpack-dev-middleware/middleware.js:105:27)
    at new Server (/home/bigpp/projects/patrickdoane.com/node_modules/webpack-dev-server/lib/Server.js:54:20)
    at Object.<anonymous> (/home/bigpp/projects/patrickdoane.com/node_modules/webpack-dev-server/bin/webpack-dev-server.js:158:12)
```
